# Generated by Django 2.1.5 on 2019-02-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='struct',
            name='idCode',
            field=models.CharField(max_length=100),
        ),
    ]
