# Generated by Django 2.1.5 on 2019-02-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0002_auto_20190219_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='struct',
            name='author',
        ),
    ]
