# Generated by Django 2.1.5 on 2019-03-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0003_remove_struct_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='struct',
            name='dateEnd',
        ),
        migrations.AlterField(
            model_name='struct',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
