# Generated by Django 2.1.5 on 2019-03-11 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0007_auto_20190308_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='struct',
            name='potReturnPer',
        ),
    ]
