# Generated by Django 2.1.5 on 2019-03-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0008_remove_struct_potreturnper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='struct',
            name='abLength',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='struct',
            name='c',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='struct',
            name='perRemain',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='struct',
            name='retracePer',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='struct',
            name='takeout',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
    ]
