# Generated by Django 2.1.5 on 2019-03-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0009_auto_20190311_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='struct',
            name='abLength',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='struct',
            name='c',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='struct',
            name='perRemain',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='struct',
            name='retracePer',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='struct',
            name='takeout',
            field=models.FloatField(),
        ),
    ]
