# Generated by Django 2.1.5 on 2019-03-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0010_auto_20190311_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='struct',
            name='abPer',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
