# Generated by Django 2.1.5 on 2019-03-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0011_struct_abper'),
    ]

    operations = [
        migrations.AddField(
            model_name='struct',
            name='group',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
