# Generated by Django 2.1.5 on 2019-03-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0013_remove_struct_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqName', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('childtime', models.CharField(max_length=100)),
                ('parTime', models.CharField(max_length=100)),
                ('indicator', models.CharField(max_length=100)),
                ('current', models.IntegerField()),
                ('thresh', models.IntegerField()),
                ('valid', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
