# Generated by Django 2.1.5 on 2019-03-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0014_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='current',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='thresh',
            field=models.FloatField(),
        ),
    ]
