# Generated by Django 2.1.5 on 2019-03-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0015_auto_20190320_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='thresh',
            field=models.FloatField(blank=True),
        ),
    ]
