# Generated by Django 2.1.5 on 2019-03-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0016_auto_20190321_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='invalid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCode', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('exchange', models.CharField(max_length=100)),
                ('eqName', models.CharField(max_length=100)),
                ('timeFrame', models.CharField(max_length=100)),
                ('bVol', models.IntegerField()),
                ('takeVol', models.IntegerField()),
                ('volDelt', models.IntegerField()),
                ('retracePer', models.FloatField()),
                ('perRemain', models.FloatField()),
                ('direction', models.CharField(max_length=100)),
                ('abPer', models.FloatField()),
                ('abLength', models.FloatField()),
                ('c', models.FloatField()),
                ('takeout', models.FloatField()),
                ('valid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Invalid Structure',
                'verbose_name_plural': 'Invalid Structures',
            },
        ),
        migrations.AlterModelOptions(
            name='struct',
            options={'ordering': ['-date'], 'verbose_name': 'Confirmed Structure', 'verbose_name_plural': 'Confirmed Structures'},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-date'], 'verbose_name': 'RSI-Watchlist Structure', 'verbose_name_plural': 'RSI-Watchlist Structures'},
        ),
    ]
