# Generated by Django 2.1.5 on 2019-04-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0017_auto_20190329_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='direction',
            field=models.CharField(default='Uptrend', max_length=100),
            preserve_default=False,
        ),
    ]
