# Generated by Django 2.1.5 on 2019-04-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0018_trade_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='struct',
            name='b',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
