# Generated by Django 2.1.5 on 2019-02-06 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchName', models.CharField(max_length=100)),
                ('timeFrame', models.IntegerField()),
                ('retracement', models.IntegerField()),
                ('cdLeg', models.IntegerField()),
                ('perRemain', models.IntegerField()),
                ('volDelt', models.IntegerField()),
                ('dateRange', models.CharField(max_length=100)),
                ('freq', models.IntegerField()),
                ('save', models.CharField(max_length=100)),
                ('send', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
