# Generated by Django 2.1.5 on 2019-02-07 01:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190206_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='dateRange',
        ),
        migrations.AddField(
            model_name='search',
            name='dateEnd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
