# Generated by Django 2.1.5 on 2019-02-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190207_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='exchange',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='search',
            name='dateEnd',
            field=models.DateField(),
        ),
    ]
