# Generated by Django 2.1.5 on 2019-02-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190207_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='timeFrame',
            field=models.PositiveIntegerField(),
        ),
    ]
