# Generated by Django 2.1.5 on 2019-02-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190209_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='specificEq',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='search',
            name='cdLeg',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='search',
            name='freq',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='perRemain',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='search',
            name='retracement',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='search',
            name='timeFrame',
            field=models.CharField(max_length=100),
        ),
    ]
