# Generated by Django 2.1.5 on 2019-02-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190209_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='cdLeg',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='search',
            name='perRemain',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='search',
            name='retracement',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
