# Generated by Django 2.1.5 on 2019-03-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190213_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='cdLeg',
        ),
        migrations.RemoveField(
            model_name='search',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='search',
            name='keep',
        ),
        migrations.RemoveField(
            model_name='search',
            name='perRemain',
        ),
        migrations.RemoveField(
            model_name='search',
            name='retracement',
        ),
        migrations.RemoveField(
            model_name='search',
            name='volDelt',
        ),
    ]
