# Generated by Django 2.1.5 on 2019-03-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190311_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='sp500',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
