# Generated by Django 2.1.5 on 2019-03-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_search_sp500'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='specif',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='search',
            name='sp500',
            field=models.BooleanField(),
        ),
    ]
