# Generated by Django 2.1.5 on 2019-03-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190311_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='sp500',
        ),
        migrations.AlterField(
            model_name='search',
            name='specif',
            field=models.CharField(max_length=100),
        ),
    ]
