# Generated by Django 2.1.5 on 2019-03-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190312_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='search',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
