# Generated by Django 2.1.5 on 2019-03-15 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_auto_20190312_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchName', models.CharField(max_length=100)),
                ('specif', models.CharField(max_length=100)),
                ('specificEq', models.CharField(blank=True, default='', max_length=100)),
                ('timeFrame', models.CharField(max_length=100)),
                ('retracement', models.FloatField()),
                ('cdLeg', models.FloatField()),
                ('extension', models.FloatField()),
                ('volDelt', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['-date']},
        ),
    ]
