# Generated by Django 2.1.5 on 2019-03-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_watch_abper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='cdLeg',
        ),
    ]
