# Generated by Django 2.1.5 on 2019-03-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190315_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='description',
            field=models.CharField(default='Tests and stuff', max_length=200),
            preserve_default=False,
        ),
    ]
