# Generated by Django 2.1.5 on 2019-03-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_watch_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='abper',
            new_name='abPer',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='extension',
            new_name='perRemain',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='retracement',
            new_name='retracePer',
        ),
    ]
