# Generated by Django 2.1.5 on 2019-03-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190315_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='description',
        ),
    ]
