# Generated by Django 2.1.5 on 2019-03-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_hot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hot',
            name='timeFrame1',
        ),
        migrations.RemoveField(
            model_name='hot',
            name='timeFrame2',
        ),
        migrations.RemoveField(
            model_name='hot',
            name='timeFrame3',
        ),
        migrations.AddField(
            model_name='hot',
            name='value1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hot',
            name='value2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hot',
            name='value3',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
