# Generated by Django 2.1.5 on 2019-03-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20190320_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='hot',
            name='maxormin1',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hot',
            name='maxormin2',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hot',
            name='maxormin3',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
