# Generated by Django 2.1.5 on 2019-03-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20190320_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hot',
            name='indicator1',
        ),
        migrations.RemoveField(
            model_name='hot',
            name='indicator2',
        ),
        migrations.RemoveField(
            model_name='hot',
            name='indicator3',
        ),
        migrations.RemoveField(
            model_name='hot',
            name='maxormin1',
        ),
        migrations.RemoveField(
            model_name='hot',
            name='maxormin2',
        ),
        migrations.RemoveField(
            model_name='hot',
            name='maxormin3',
        ),
        migrations.AddField(
            model_name='hot',
            name='maxormin',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hot',
            name='value4',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hot',
            name='value5',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hot',
            name='value6',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
