# Generated by Django 2.1.5 on 2019-03-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20190321_2259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hot',
            new_name='hotlist',
        ),
    ]
