# Generated by Django 2.1.5 on 2019-03-27 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20190322_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='dateEnd',
        ),
    ]
