# Generated by Django 2.1.5 on 2019-03-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_search_dateend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotlist',
            options={'verbose_name': 'Hotlist Search', 'verbose_name_plural': 'Hotlist Searches'},
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['-date'], 'verbose_name': 'CS Search', 'verbose_name_plural': 'CS Searches'},
        ),
        migrations.AlterModelOptions(
            name='watch',
            options={'ordering': ['-date'], 'verbose_name': 'Watchlist Search', 'verbose_name_plural': 'Watchlist Searches'},
        ),
    ]
