# Generated by Django 2.1.5 on 2019-04-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20190329_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='abPer',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='perRemain',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='retracePer',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='volDelt',
            field=models.IntegerField(blank=True),
        ),
    ]
