# Generated by Django 2.1.5 on 2019-04-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20190408_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='volDelt',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
