# Generated by Django 2.1.5 on 2019-04-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20190408_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='volDelt',
            field=models.BooleanField(null=True),
        ),
    ]
