# Generated by Django 2.1.5 on 2019-04-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20190408_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotlist',
            name='maxormin',
            field=models.BooleanField(max_length=100),
        ),
    ]
